version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    working_directory: ~/repo

    steps:
      - run: yarn install
      - run: ./node_modules/.bin/elm package install

      - run: ./node_modules/.bin/elm-make app/Main.elm --output build/app.js --warn
      - run: ./node_modules/.bin/elm-test
